#!/bin/bash

# for description see:
# /usr/share/modalai/voxl-camera-server/custom_camera_config.txt

J6_LOWER_SENSOR="ov7251-combo"
J6_LOWER_NAME="stereo"
J6_LOWER_COMBO_MODE="left-right"
J6_LOWER_ROTATE="false"


J7_LOWER_SENSOR="ov7251"
J7_LOWER_NAME="tracking"
J7_LOWER_ROTATE="false"
