#!/bin/bash

# for description see:
# /usr/share/modalai/voxl-camera-server/custom_camera_config.txt

J6_LOWER_SENSOR="pmd-tof"
J6_LOWER_NAME="tof"


J7_LOWER_SENSOR="imx214"
J7_LOWER_NAME="hires"
J7_LOWER_ROTATE="false"


J7_UPPER_SENSOR="ov7251"
J7_UPPER_NAME="tracking"
J7_UPPER_ROTATE="false"
