#!/bin/bash

# for description see:
# /usr/share/modalai/voxl-camera-server/custom_camera_config.txt



J7_LOWER_SENSOR="imx412"
J7_LOWER_NAME="hires"
J7_LOWER_ROTATE="true"


J7_UPPER_SENSOR="ar0144"
J7_UPPER_NAME="tracking"
J7_UPPER_ROTATE="false"
