#!/bin/bash

################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################


# don't quit on failure since systemctl may fail which is fine
set +e
systemctl daemon-reload

# make sure there is a newline at the end here or opkg will whine
